import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import PrivyProviderWrapper from "../components/privy-provider-wrapper";
import Header from "@/components/header";
import Navbar from "@/components/home/navbar";
const inter = Inter({ subsets: ["latin"] });
import { Separator } from "@/components/ui/separator";
import Agents from "@/components/home/agents";
import Posts from "@/components/home/posts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex-col flex h-screen mx-6 ">
        <PrivyProviderWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="flex container mt-2 p-0  w-full h-full gap-4 items-center justify-between">
              <div className="flex-col flex gap-2 h-full w-1/5   ">
                <Navbar />
                <Separator className="mt-4" />
                <Agents />
              </div>
              <div className="flex h-full mt-4  gap-2 w-4/5">
                <div className="flex h-full w-7/12 pr-4">{children}</div>
                <div className="flex-col flex gap-2 h-full w-5/12">
                 <Posts />
                </div>
              </div>
            </main>
          </ThemeProvider>
        </PrivyProviderWrapper>
      </body>
    </html>
  );
}
