import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import PrivyProviderWrapper from "../components/privy-provider-wrapper";
import Header from "@/components/header";
import Navbar from "@/components/home/navbar";
const inter = Inter({ subsets: ["latin"] });
import { Separator } from "@/components/ui/separator";
import Agents from "@/components/home/agents";
import Posts from "@/components/home/posts";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/app/providers";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex-col flex h-screen mx-2 md:mx-6   ">
        <PrivyProviderWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
            <Header />
            <main className="flex container mt-2 p-0 w-full h-full gap-4 items-center justify-between"  >
              <div className="hidden md:flex-col md:flex gap-2 h-full w-1/6 border-r pr-2   ">
                <Navbar />
                <Agents />
              </div>
              <div className="flex h-full  w-full md:w-5/6">
              {children}
              </div>
            
            </main>
            <Toaster />
            </Providers>
        
          </ThemeProvider>
        </PrivyProviderWrapper>
      </body>
    </html>
  );
}
